name:        gibbr
version:     v0.3.0
summary:     gibbr is a utility for scrambling filenames.
confinement: strict
description: gibbr is a utility for scrambling filenames.

apps:
  gibbr:
    command: bin/gibbr
    plugs: [home]

parts:
  gibbr:
    plugin: nodejs
    node-packages:
      - rgrannell1/gibbr

