name:        gibbr
version:     v0.3.0
summary:     gibbr is a utility for scrambling filenames.
description: >
  gibbr is a utility for scrambling filenames.

apps:
  gibbr:
    command: src/cli/gibbr.js

parts:
  gibbr:
    plugin: nodejs
    node-packages:
      - rgrannell1/gibbr
